"""empty message

Revision ID: 529a7750a835
Revises: d9ce5b1337ec
Create Date: 2023-07-15 21:58:20.851077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529a7750a835'
down_revision = 'd9ce5b1337ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
